### PR TITLE
Ready

### PR DESCRIPTION
**Pull request by jon-arnold**
Added a brief definition of ready and done to our dev process.

I would love the team to comment on this to flesh out what you’d like
to see improved with pre-development planning

### CODE REVIEW

**Comment by comike011** [comment]
@jon-arnold I like this alot. Would like input from @derekblank and @mollytaryn

**Comment by derekblank** [comment]
Methinks it looks great as well. Similarly related to the addition to the definition of Ready, I was curious when reading through the Work in Progress section about how we should handle concurrent stories that are "On Hold" but still In Progress (like the current Blog CMS state, for instance).

**Comment by mollytaryn** [comment]
@jon-arnold - I also think this is a great addition. One thought on the definition of done. Do we want to say anything about the feature / bug / task having test coverage / passing tests? This may be obvious to the existing members of our team, but not necessarily a new team member. Since we are trying to keep test coverage high, might be good to be explicit about this. My only other comment - is the definition of ready / done different for bugs and features? A lot of the items added here seem more applicable to a new feature.

**Comment by comike011** [comment]
@lvhdev/owners Im going to merge this guy in, @mollytaryn would you take point on a new pull request for test coverage and passing?

**Pull request merged**
